name: flutter_notes
description: An app to take notes, made with Flutter.
repository: https://github.com/FerMod/flutter_notes
issue_tracker: https://github.com/FerMod/flutter_notes/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number of the application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.3-beta.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Internationalization support.
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_localized_locales: ^2.0.5
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  url_strategy: ^0.2.0
  universal_platform: ^1.0.0+1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/flutter_notes_logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
